# Python try ...finally
# In Python, the finally block is always executed no matter whether there is an exception or not .

# The finally block is optional. And, for each try block, there can be only one finally block.
